### PR TITLE
feat: 🎸 changed app icon

### PR DESCRIPTION
**Pull request by UmarAuna**

### CODE REVIEW

**Comment by ugoamanoh** [comment]
@UmarAuna I don't see your source code in this pull request

**Comment by UmarAuna** [comment]
@ugoamanoh its because i merge my code but you can view the what i changed here https://github.com/UmarAuna/Cars/pull/3/commits/aec04cd2e48d5e33865a77910d3e88f7634359b2

**Comment by ugoamanoh** [comment]
@UmarAuna I don't see where the filtration is being done when I look through your code [https://github.com/UmarAuna/Cars/compare/43145b97fad7f44c4acf67e00af8822f9b070fc8...master](here).

Also, when using `CardView` you seem to wrap all the `TextView` in a `LinearLayout` any reason why?

**Comment by UmarAuna** [comment]
@ugoamanoh I sometimes prefer using `LinearLayout` to wrap my `Views` to make them in order and regarding the filtration, I couldn't find time to do it and today is the deadline.

**Pull request merged**
